### ISSUE TITLE
bug: animate on hover

### ISSUE THREAD

**Issue by antoniel** [lucasfloriani/re-uno#4]
# Bug description
This error occurs when hover card component at the bottom, so when component is translated there's no more hover

# Solution
Apply animation effect on pseudo element or something like this,  im not sure if tailwind supports pseudo-elements so this should be handled by css.

![Kapture 2021-05-03 at 16 17 40](https://user-images.githubusercontent.com/17225358/116922173-5a179c00-ac2b-11eb-9f69-cefd85fd2298.gif)

**Comment by lucasfloriani** [comment]
@all-contributors please add @antoniel for bug and code
